### PR TITLE
add copyright license in lice

### PR DESCRIPTION
**Pull request by nichdemos**
Hey y'all!

Added [copyright license](https://copyfree.org/policy/copyright) on lice. I want to contribute in the best way possible to this first open source project that interests me.

### CODE REVIEW

**Review by ralyodio — APPROVED** [review]

**Comment by nichdemos** [comment]
Hi @ralyodio, thanks!

**Comment by ralyodio** [comment]
need @superkhau to release a new version.

**Comment by superkhau** [comment]
Hey guys, sorry for the late reply -- waiting on NPM to reset my PW.  Their system is messed, but we'll get this released as soon it's resolved.

**Comment by superkhau** [comment]
Done

**Pull request merged**
